# Generated by Django 5.2 on 2025-05-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_breaking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_sponsored',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_trending',
            field=models.BooleanField(default=True),
        ),
    ]
